### ISSUE TITLE
Styled JSX is best choice

### ISSUE THREAD

**Issue by comerc** [oliviertassinari/a-journey-toward-better-style#4]
https://github.com/zeit/styled-jsx

We have the same advantages. Plus native CSS for editing (vs JS-Objects). It is very important feature for copy-paste.

**Comment by oliviertassinari** [comment]
Thanks for sharing that solution, it's interesting. One limitation I can think of is regarding the dynamic style injection. Also, I'm not sure how override order are guaranteed.

**Comment by comerc** [comment]
Please see here:
[Dynamic styles](https://github.com/zeit/styled-jsx#dynamic-styles)
[Constants and Config](https://github.com/zeit/styled-jsx#constants-and-config)

**Comment by comerc** [comment]
[styled-jsx-postcss](https://github.com/giuseppeg/styled-jsx-postcss) - it is very big advantage!
